# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  setup-web-server:
    if: "contains(github.event.head_commit.message, 'build-server')"
    runs-on: ubuntu-latest

    env:
      RESOURCE_GROUP: group-project1
      DISK_NAME: lab1_DataDisk_0
      VM_SIZE: Standard_B1s
      VM_NAME: lab1
      VM_IMAGE: Canonical:0001-com-ubuntu-server-focal:20_04-lts-gen2:20.04.202101191

    steps:
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    - name: Clear resource
      run: |
        az vm delete -g $RESOURCE_GROUP -n $VM_NAME -y
        az disk delete --name $DISK_NAME --resource-group $RESOURCE_GROUP -y
    - name: Create disk
      run: |
        az disk create --name $DISK_NAME \
          --resource-group $RESOURCE_GROUP \
          --size-gb 8
    - name: Create VM
      run: |
        az vm create --resource-group $RESOURCE_GROUP \
          --name $VM_NAME \
          --image $VM_IMAGE \
          --authentication-type password \
          --admin-username ${{ secrets.AZURE_USER }} \
          --admin-password ${{ secrets.AZURE_PASSWORD }} \
          --attach-data-disks $DISK_NAME \
          --size $VM_SIZE \
          --output none \
          --verbose
    - name: Get public ip
      run: |
        IP=$(az vm show -d -g $RESOURCE_GROUP -n $VM_NAME --query publicIps -o tsv)
        echo "::set-env name=IP::$IP"
    - name: Delete DNS record set
      run: |
        az network dns record-set a delete --name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} -y
        echo $IP
    - name: Create a new DNS record
      run: |
        az network dns record-set a create --name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} -o none
        az network dns record-set a add-record --ipv4-address $IP \
          --record-set-name @ \
          --resource-group $RESOURCE_GROUP \
          --zone-name ${{ secrets.HOSTNAME }} \
          --ttl 300 -o none

  build:

    needs: [setup-web-server]
    if: always()
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Test print dir
      run: |
        ls -la
        ls -l target
        pwd
